# Generated by Django 3.2.6 on 2021-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.IntegerField(unique=True),
        ),
    ]
