# Generated by Django 3.2.6 on 2021-09-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20210906_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='maintainer',
            new_name='creator',
        ),
    ]
