# Generated by Django 3.2.6 on 2021-10-07 11:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0006_alter_project_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
