# Generated by Django 3.2.6 on 2021-09-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=10)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wiki', models.CharField(max_length=500)),
                ('maintainer', models.IntegerField()),
                ('team_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.appuser')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.list')),
            ],
        ),
    ]
