# Generated by Django 3.2.6 on 2021-09-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trelloapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='maintainer',
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trelloapp.appuser')),
            ],
        ),
    ]
